// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFA1H0zNgAWgDxTiZvYJPd3CsJiwDgi4I',
    appId: '1:248321898441:android:6604657023976bdfc11a18',
    messagingSenderId: '248321898441',
    projectId: 'neurodyx-e262d',
    storageBucket: 'neurodyx-e262d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ERo5xr0jMueGceq5mqAR12qMTtNaXS4',
    appId: '1:248321898441:ios:3dc2f6fa0da673a5c11a18',
    messagingSenderId: '248321898441',
    projectId: 'neurodyx-e262d',
    storageBucket: 'neurodyx-e262d.firebasestorage.app',
    androidClientId: '248321898441-hq4d8rseog51o9u2tc8dsrjkp9958ope.apps.googleusercontent.com',
    iosClientId: '248321898441-gmucdshfjhmbhhl7n3odqsrpccgq2385.apps.googleusercontent.com',
    iosBundleId: 'com.example.neurodyx',
  );

}